name: amal
description: ""
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_slidable: ^3.0.1
  google_maps_flutter: ^2.5.3
  image_picker: ^1.0.7
  latlong2: ^0.9.0
  lecle_bubble_timeline: ^0.0.1+1
  path_provider: ^2.1.2
  url_launcher: ^6.2.5
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/