// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwnUYsMQsmPnE91xsQNm6-rNU5CVispXY',
    appId: '1:829934569895:web:f9ddb2fe23c5ea3bbdce82',
    messagingSenderId: '829934569895',
    projectId: 'amal-11013',
    authDomain: 'amal-11013.firebaseapp.com',
    storageBucket: 'amal-11013.appspot.com',
    measurementId: 'G-NHT2L5VRVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNYBSRbz9AevM87EfnxSdTK3joTCp1PvE',
    appId: '1:829934569895:android:ac1afc3a2f5afa73bdce82',
    messagingSenderId: '829934569895',
    projectId: 'amal-11013',
    storageBucket: 'amal-11013.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdO79QlExYKDkO5H974JypyFwRzQqmDQU',
    appId: '1:829934569895:ios:55ea772ba3dcb859bdce82',
    messagingSenderId: '829934569895',
    projectId: 'amal-11013',
    storageBucket: 'amal-11013.appspot.com',
    iosBundleId: 'com.example.amal',
  );
}
